# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "keepalived", path: "../keepalived"
cookbook "haproxy", path: "../haproxy"
cookbook "base", path: "../base"
cookbook 'chef-client', '~> 10.0.3'
