# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook "keepalived", path: "../keepalived"
cookbook "haproxy", path: "../haproxy"
cookbook "default-packages", path: "../default-packages"
